var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/datagov_db');
var LocationsSchema = new mongoose.Schema({
    Sunday : {
        type: String
    },
    Monday : {
        type: String
    },
    Tuesday : {
        type: String
    },
    Wednesday : {
        type: String
    },
    Thursday : {
        type: String
    },
    Friday : {
        type: String
    },
    Saturday : {
        type: String
    },
    Duration_Hours : {
        type: String
    },
    Day_Time : {
        type: String
    },
    Meal_Served : {
        type: String
    },
    People_Served : {
        type: String
    },
    Address : {
        type: String
    },
    Location : {
        type: String
    },
    Name_of_Program : {
        type: String
    },
})
mongoose.model('locations', LocationsSchema);
var locations = mongoose.model('locations');

dataset = [
    {
      "Sunday": "",
      "Monday": "6:15:00 AM",
      "Tuesday": "6:15:00 AM",
      "Wednesday": "6:15:00 AM",
      "Thursday": "6:15:00 AM",
      "Friday": "6:15:00 AM",
      "Saturday": "",
      "Duration_Hours": 0.75,
      "Day_Time": "Monday - Friday: 6:15 - 7:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "2515 Western Ave., Seattle",
      "Location": "2515 Western Ave., Seattle",
      "Name_of_Program": "Millionair Club Charity"
    },
    {
      "Sunday": "5:30:00 AM",
      "Monday": "5:30:00 AM",
      "Tuesday": "5:30:00 AM",
      "Wednesday": "5:30:00 AM",
      "Thursday": "5:30:00 AM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 3,
      "Day_Time": "Sunday - Thursday 5:30 - 8:30 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "8201 10th Ave S., Seattle",
      "Location": "8201 10th Ave S., Seattle",
      "Name_of_Program": "South Park Breakfast Bunch"
    },
    {
      "Sunday": "",
      "Monday": "7:00:00 AM",
      "Tuesday": "7:00:00 AM",
      "Wednesday": "7:00:00 AM",
      "Thursday": "7:00:00 AM",
      "Friday": "7:00:00 AM",
      "Saturday": "",
      "Duration_Hours": 2.5,
      "Day_Time": "Monday - Friday 7:00 - 9:30 A.M.",
      "Meal_Served": "",
      "People_Served": "AMERICAN INDIANS ONLY",
      "Address": "410 2nd Ave. Extension So., Seattle",
      "Location": "410 2nd Ave. Extension So., Seattle",
      "Name_of_Program": "Chief Seattle Club"
    },
    {
      "Sunday": "7:00:00 AM",
      "Monday": "7:00:00 AM",
      "Tuesday": "7:00:00 AM",
      "Wednesday": "7:00:00 AM",
      "Thursday": "7:00:00 AM",
      "Friday": "7:00:00 AM",
      "Saturday": "7:00:00 AM",
      "Duration_Hours": 2,
      "Day_Time": "Chapel required prior to meal service. There are 3 daily Chapel services to choose from: 7-7:30 A.M., 7:45-8:15 A.M., 8:30-9 A.M.  (Meal served following each service.)",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "318 2nd Ave. S. Extension,  Seattle",
      "Location": "318 2nd Ave. S. Extension,  Seattle",
      "Name_of_Program": "Union Gospel Mission"
    },
    {
      "Sunday": "",
      "Monday": "8:30:00 AM",
      "Tuesday": "8:30:00 AM",
      "Wednesday": "8:30:00 AM",
      "Thursday": "8:30:00 AM",
      "Friday": "8:30:00 AM",
      "Saturday": "",
      "Duration_Hours": 2.5,
      "Day_Time": "Monday - Friday: 8:30 - 11:00 A.M. (Sack lunch for the day)",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "232 Warren Ave. North, Suite B, Seattle",
      "Location": "232 Warren Ave. North, Suite B, Seattle",
      "Name_of_Program": "Sacred Heart Church/SVDP Society"
    },
    {
      "Sunday": "7:20:00 AM",
      "Monday": "7:20:00 AM",
      "Tuesday": "7:20:00 AM",
      "Wednesday": "7:20:00 AM",
      "Thursday": "7:20:00 AM",
      "Friday": "7:20:00 AM",
      "Saturday": "7:20:00 AM",
      "Duration_Hours": 0.5,
      "Day_Time": "Daily: 1st seating is 7:20 - 7:50 A.M. (overnight guests only)                                                               2nd seating is 8:10 - 8:40 A.M. (day program clients)",
      "Meal_Served": "Breakfast",
      "People_Served": "WOMEN 18 AND OLDER",
      "Address": "2030 3rd Ave, Seattle",
      "Location": "2030 3rd Ave, Seattle",
      "Name_of_Program": "YWCA Angeline's Meals Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "3 Breakfasts per week on variable days: 8:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO 55+",
      "Address": "85 Pike St.  #200,  Seattle",
      "Location": "85 Pike St.  #200,  Seattle",
      "Name_of_Program": "Pike Market Senior Center"
    },
    {
      "Sunday": "8:00:00 AM",
      "Monday": "8:00:00 AM",
      "Tuesday": "8:00:00 AM",
      "Wednesday": "8:00:00 AM",
      "Thursday": "8:00:00 AM",
      "Friday": "8:00:00 AM",
      "Saturday": "8:00:00 AM",
      "Duration_Hours": "",
      "Day_Time": "Daily: 8:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO MEN 50+",
      "Address": "1561 Alaskan Way S.,  Seattle",
      "Location": "1561 Alaskan Way S.,  Seattle",
      "Name_of_Program": "Saint Martin's de Porres Shelter"
    },
    {
      "Sunday": "",
      "Monday": "8:00:00 AM",
      "Tuesday": "8:00:00 AM",
      "Wednesday": "8:00:00 AM",
      "Thursday": "8:00:00 AM",
      "Friday": "8:00:00 AM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Monday - Friday: Breakfast 8:00 - 9:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Operation Sack Lunch"
    },
    {
      "Sunday": "",
      "Monday": "8:30:00 AM",
      "Tuesday": "8:30:00 AM",
      "Wednesday": "8:30:00 AM",
      "Thursday": "8:30:00 AM",
      "Friday": "8:30:00 AM",
      "Saturday": "10:00:00 AM",
      "Duration_Hours": 1,
      "Day_Time": "Monday - Friday: 8:30 - 9:30 A.M.; Saturdays: 10:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO WOMEN & CHILDREN ONLY",
      "Address": "210 Dexter Avenue, Seattle",
      "Location": "210 Dexter Avenue, Seattle",
      "Name_of_Program": "Mary's Place / Church of Mary Magdalene"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Tuesday - Sunday: 9:00 - 11:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "508 Broadway, Seattle",
      "Location": "508 Broadway, Seattle",
      "Name_of_Program": "Our Lady of Mt. Carmel"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "3rd Sunday: Hot Brunch 10:00  - 11:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Mother's Kitchen"
    },
    {
      "Sunday": "",
      "Monday": "10:00:00 AM",
      "Tuesday": "10:00:00 AM",
      "Wednesday": "",
      "Thursday": "10:00:00 AM",
      "Friday": "10:00:00 AM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Mon, Tues, Thurs, & Fri: 10:00  - 11:00 A.M.",
      "Meal_Served": "Breakfast",
      "People_Served": "YOUTH 22 AND YOUNGER",
      "Address": "2709 3rd Ave., Seattle",
      "Location": "2709 3rd Ave., Seattle",
      "Name_of_Program": "New Horizons Ministries"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Last Sunday of Each Month / November - March: 8:00 - 10:00 AM",
      "Meal_Served": "Breakfast",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Magic Works Alumni"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "10:30:00 AM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Fridays: 10:30 A.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "919 King Street, Seattle",
      "Location": "919 King Street, Seattle",
      "Name_of_Program": "ACRS Food Bank"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "11:00:00 AM",
      "Wednesday": "11:00:00 AM",
      "Thursday": "11:00:00 AM",
      "Friday": "11:00:00 AM",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Tuesday through Friday: 11:00 A.M.- 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO YOUTH UP TO  AGE 21",
      "Address": "1814 Summit Ave.,  Seattle",
      "Location": "1814 Summit Ave.,  Seattle",
      "Name_of_Program": "(PSKS) Peace for the Streets by Kids from the Streets"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "2nd  and 4th Sunday: 11:00 A.M. to 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Set Free Ministries"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "11:00:00 AM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Tuesdays: 11:00 A.M. - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "Primarily low-income Samoan seniors",
      "Address": "3204 SW Holly St., Seattle",
      "Location": "3204 SW Holly St., Seattle (Holly Park Comm. Center)",
      "Name_of_Program": "Samoana Senior Club"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "11:00:00 AM",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Fridays: 11:00 A.M. - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "Primarily low-income Tongan & PI Seniors",
      "Address": "2801 SW Thistle Street, Seattle",
      "Location": "2801 SW Thistle Street, Seattle",
      "Name_of_Program": "Friendly Island of Tonga Seniors"
    },
    {
      "Sunday": "11:30:00 AM",
      "Monday": "11:30:00 AM",
      "Tuesday": "11:30:00 AM",
      "Wednesday": "11:30:00 AM",
      "Thursday": "11:30:00 AM",
      "Friday": "11:30:00 AM",
      "Saturday": "11:30:00 AM",
      "Duration_Hours": 1.5,
      "Day_Time": "Daily  1st seating: 11:30 A.M. -12:00 P.M.,  2nd seating: 12:30-1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "WOMEN 18 AND OLDER",
      "Address": "2030 3rd Ave, Seattle",
      "Location": "2030 3rd Ave, Seattle",
      "Name_of_Program": "YWCA Angeline's Meals Program"
    },
    {
      "Sunday": "",
      "Monday": "11:30:00 AM",
      "Tuesday": "11:30:00 AM",
      "Wednesday": "11:30:00 AM",
      "Thursday": "11:30:00 AM",
      "Friday": "11:30:00 AM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Monday - Friday: 11:30 A.M.. - 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO AGES 60+",
      "Address": "409 Maynard Ave South, Seattle",
      "Location": "409 Maynard Ave South, Seattle",
      "Name_of_Program": "Legacy House Nutrition Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "11:30:00 AM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "11:30:00 AM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Tuesday and Friday 11:30 A.M. - 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "3639 Martin Luther King Way, Seattle",
      "Location": "3639 Martin Luther King Way, Seattle",
      "Name_of_Program": "Emergency Senior Nutrition Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "11:30:00 AM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Fridays: 11:30 A.M. - 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "5710 22nd Ave. NW  Seattle",
      "Location": "5710 22nd Ave. NW  Seattle",
      "Name_of_Program": "Saint Luke's Episcopal Church"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "11:30:00 AM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Tuesdays: 11:30 A.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "8201 10th Ave South, Seattle",
      "Location": "8201 10th Ave South, Seattle",
      "Name_of_Program": "Latino Lunch"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "11:30:00 AM",
      "Thursday": "",
      "Friday": "11:30:00 AM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Wednesday & Friday: 11:30 A.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "8201 10th Ave South, Seattle",
      "Location": "8201 10th Ave South, Seattle",
      "Name_of_Program": "PAEP/Polynesian Nutrition Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "11:30:00 AM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "11:30:00 AM",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "Tuesdays & Fridays: 11:30 A.M. - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "Primarily low-income Samoans",
      "Address": "330 19th Ave, Seattle",
      "Location": "330 19th Ave, Seattle",
      "Name_of_Program": "ACRS/Korean Senior Club"
    },
    {
      "Sunday": "",
      "Monday": "12:00:00 PM",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 0.75,
      "Day_Time": "Monday - Friday: 12:00 - 12:45 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL /            Must be sober",
      "Address": "611 12th Ave South, Suite 300, Seattle",
      "Location": "611 12th Ave South, Suite 300, Seattle",
      "Name_of_Program": "Seattle Indian Center"
    },
    {
      "Sunday": "11:00:00 AM",
      "Monday": "11:00:00 AM",
      "Tuesday": "11:00:00 AM",
      "Wednesday": "11:00:00 AM",
      "Thursday": "11:00:00 AM",
      "Friday": "11:00:00 AM",
      "Saturday": "11:00:00 AM",
      "Duration_Hours": 1,
      "Day_Time": "Chapel required prior to meal service.  Please arrive between 11:00 - 11:30 A.M., chapel begins at 11:30 A.M., meal is served at 12:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "318 2nd Ave. S. Extension,  Seattle",
      "Location": "318 2nd Ave. S. Extension,  Seattle",
      "Name_of_Program": "Union Gospel Mission"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "12:00:00 PM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Thursdays: 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "31957 E. Commercial Street, Carnation",
      "Location": "31957 E. Commercial Street, Carnation",
      "Name_of_Program": "Hopelink/Sno-Valley"
    },
    {
      "Sunday": "12:00:00 PM",
      "Monday": "12:00:00 PM",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "12:00:00 PM",
      "Duration_Hours": "",
      "Day_Time": "Daily: 12:00 P.M. (Closed 1st Wednesday of each month)",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO 55+",
      "Address": "85 Pike St.  #200,  Seattle",
      "Location": "85 Pike St.  #200,  Seattle",
      "Name_of_Program": "Pike Market Senior Center"
    },
    {
      "Sunday": "12:00:00 PM",
      "Monday": "12:00:00 PM",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "12:00:00 PM",
      "Duration_Hours": 2,
      "Day_Time": "Daily: 12:00  - 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO 50+",
      "Address": "416 Second Ave Extension South, Seattle",
      "Location": "416 Second Ave Extension South, Seattle",
      "Name_of_Program": "Lazurus Day Center"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "12:00:00 PM",
      "Duration_Hours": 1,
      "Day_Time": "Every Saturday : 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Bible Study Out Reach Ministries"
    },
    {
      "Sunday": "12:00:00 PM",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Every Sunday 12:00 - 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "5050 8th Ave. NE,  Seattle",
      "Location": "5050 8th Ave. NE,  Seattle",
      "Name_of_Program": "Blessed Sacrament Church Sunday Dinner"
    },
    {
      "Sunday": "",
      "Monday": "12:00:00 PM",
      "Tuesday": "",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Mon, Wed, Thurs, Friday - Sack Lunch 12 P.M., Tue - 12:30 P.M. (Hot Lunch)",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "97 South Main St.,  Seattle",
      "Location": "97 South Main St.,  Seattle",
      "Name_of_Program": "Bread of Life Mission"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "12:00:00 PM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Tuesday & Friday: 12:00 P.M. (noon)",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "1710 11th Ave., Seattle",
      "Location": "1710 11th Ave., Seattle",
      "Name_of_Program": "Community Lunch on Capitol Hill"
    },
    {
      "Sunday": "",
      "Monday": "12:00:00 PM",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Monday - Friday: 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "2524 16th Ave. S, Seattle",
      "Location": "2524 16th Ave. S, Seattle",
      "Name_of_Program": "El Centro de La Raza"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "Last Sunday of each month: 12:00 - 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "1215 Thomas St., Seattle",
      "Location": "1215 Thomas St., Seattle",
      "Name_of_Program": "Community Lunch / Immanuel Community Services"
    },
    {
      "Sunday": "",
      "Monday": "12:00:00 PM",
      "Tuesday": "12:00:00 PM",
      "Wednesday": "12:00:00 PM",
      "Thursday": "12:00:00 PM",
      "Friday": "12:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "Monday - Friday: 12:00 - 1:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "2515 Western Ave.,  Seattle",
      "Location": "2515 Western Ave.,  Seattle",
      "Name_of_Program": "Millionair Club Charity"
    },
    {
      "Sunday": "",
      "Monday": "12:00:00 PM",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Mondays: 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "Calvary Lutheran, 7002 23rd Ave NW, Seattle",
      "Location": "Calvary Lutheran                      7002 23rd Ave NW, Seattle",
      "Name_of_Program": "Phinney Neighborhood Association"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "12:00:00 PM",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Wednesdays: 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "St. John's Lutheran, 5515 Phinney Ave N., Seattle",
      "Location": "St. John's Lutheran                 5515 Phinney Ave N., Seattle",
      "Name_of_Program": "Phinney Neighborhood Association"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "3rd Sunday: 12:00 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Anonomous Acts of Kindness"
    },
    {
      "Sunday": "",
      "Monday": "12:30:00 PM",
      "Tuesday": "12:30:00 PM",
      "Wednesday": "12:30:00 PM",
      "Thursday": "12:30:00 PM",
      "Friday": "12:30:00 PM",
      "Saturday": "",
      "Duration_Hours": 0.5,
      "Day_Time": "Monday - Friday: 12:30 - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "Youth 13-21",
      "Address": "1828 Yale Avenue",
      "Location": "1828 Yale Avenue (on the corner of Denny and Stewart)",
      "Name_of_Program": "Youth Care's Orion Center"
    },
    {
      "Sunday": "",
      "Monday": "12:30:00 PM",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 0.5,
      "Day_Time": "Mondays: 12:30  - 1:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "Woodland Park Pres. Church 225 N. 70th, Seattle",
      "Location": "Woodland Park Pres. Church 225 N. 70th, Seattle",
      "Name_of_Program": "Monday Feeding Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "12:30:00 PM",
      "Wednesday": "",
      "Thursday": "12:30:00 PM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Tuesday & Thursday: 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "5740 MLK Jr. Way South, Seattle",
      "Location": "5740 MLK Jr. Way South, Seattle",
      "Name_of_Program": "PAEP/Filipino Senior Services"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "12:30:00 PM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "12:30:00 PM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Tuesday & Friday; 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6721 51st Ave South, Seattle",
      "Location": "6721 51st Ave South, Seattle",
      "Name_of_Program": "PAEP/Laotian & H'mong Senior Srvcs."
    },
    {
      "Sunday": "",
      "Monday": "12:30:00 PM",
      "Tuesday": "12:30:00 PM",
      "Wednesday": "12:30:00 PM",
      "Thursday": "12:30:00 PM",
      "Friday": "12:30:00 PM",
      "Saturday": "12:30:00 PM",
      "Duration_Hours": "",
      "Day_Time": "Monday - Saturday: 12:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO WOMEN & CHILDREN ONLY",
      "Address": "210 Dexter Avenue, Seattle",
      "Location": "210 Dexter Avenue, Seattle",
      "Name_of_Program": "Mary's Place / Church of Mary Magdalene"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "12:30:00 PM",
      "Wednesday": "12:30:00 PM",
      "Thursday": "12:30:00 PM",
      "Friday": "12:30:00 PM",
      "Saturday": "12:30:00 PM",
      "Duration_Hours": 2,
      "Day_Time": "Tuesday - Saturday: 12:30 - 2:30 P.M. (Must be sober 24 hours, must become member after 1st meal)",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "2022 Boren Avenue, Seattle",
      "Location": "2022 Boren Avenue, Seattle",
      "Name_of_Program": "Recovery Café"
    },
    {
      "Sunday": "",
      "Monday": "1:00:00 PM",
      "Tuesday": "1:00:00 PM",
      "Wednesday": "1:00:00 PM",
      "Thursday": "1:00:00 PM",
      "Friday": "1:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Monday - Friday: Lunch 1:00 - 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Operation Sack Lunch"
    },
    {
      "Sunday": "",
      "Monday": "1:15:00 PM",
      "Tuesday": "1:15:00 PM",
      "Wednesday": "1:15:00 PM",
      "Thursday": "1:15:00 PM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "1st, 2nd, and 4th Sunday: 1:00 - 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia,",
      "Name_of_Program": "Anonomous Acts of Kindness"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2.5,
      "Day_Time": "Monday - Thursday: 1:15  - 3:45 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "Drop-In Youth 12 - 22",
      "Address": "4516 15th Ave NE, Seattle",
      "Location": "4516 15th Ave NE, Seattle",
      "Name_of_Program": "U-District Youth Center"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Last Sunday of every month: 2:00 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "111 NE 80th St.  Seattle",
      "Location": "111 NE 80th St.  Seattle",
      "Name_of_Program": "Saint Andrew's Episcopal Church Jubilee Dinners"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "4th Saturday: 2:00 - 3:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Restoration Life Church"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "3rd Sunday: 2:00 - 3:30 P.M.",
      "Meal_Served": "Lunch",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Curry Temple"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "2nd Saturday: 1:00 - 2: 00 P.M.",
      "Meal_Served": "Snack",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Seeds of Abraham Pentecostal Church"
    },
    {
      "Sunday": "3:00:00 PM",
      "Monday": "3:00:00 PM",
      "Tuesday": "3:00:00 PM",
      "Wednesday": "3:00:00 PM",
      "Thursday": "3:00:00 PM",
      "Friday": "3:00:00 PM",
      "Saturday": "3:00:00 PM",
      "Duration_Hours": 0.5,
      "Day_Time": "Daily: 3:00 - 3:30 P.M.",
      "Meal_Served": "Snack",
      "People_Served": "WOMEN 18 AND OLDER",
      "Address": "2030 3rd Ave, Seattle",
      "Location": "2030 3rd Ave, Seattle",
      "Name_of_Program": "YWCA Angeline's Meals Program"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "2nd Saturday: 3:00 - 4:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Neighborhood Cooking Foundation"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "1st, 3rd and 5th Saturday: 4:00 - 5:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Mount Zion Baptist Church / Street Feeding Ministry"
    },
    {
      "Sunday": "",
      "Monday": "4:30:00 PM",
      "Tuesday": "4:30:00 PM",
      "Wednesday": "4:30:00 PM",
      "Thursday": "4:30:00 PM",
      "Friday": "4:30:00 PM",
      "Saturday": "",
      "Duration_Hours": 0.5,
      "Day_Time": "Monday - Friday: 4:30 - 5:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "Women, Children, Families, Men 55+",
      "Address": "803 Terry Ave., Seattle",
      "Location": "803 Terry Ave., Seattle",
      "Name_of_Program": "Cathedral Kitchen"
    },
    {
      "Sunday": "",
      "Monday": "4:30:00 PM",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 0.75,
      "Day_Time": "Mondays: 4:30 - 5:15 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "100 N street SE, Auburn",
      "Location": "100 N street SE, Auburn",
      "Name_of_Program": "Auburn Community Supper"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "5:00:00 PM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Tuesdays: 5:00 - 6:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "St. John's Lutheran                 5515 Phinney Ave N., Seattle",
      "Location": "St. John's Lutheran                 5515 Phinney Ave N., Seattle",
      "Name_of_Program": "Phinney Neighborhood Association"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "5:15:00 PM",
      "Wednesday": "5:15:00 PM",
      "Thursday": "5:15:00 PM",
      "Friday": "5:15:00 PM",
      "Saturday": "5:15:00 PM",
      "Duration_Hours": 0.75,
      "Day_Time": "Tuesday - Saturday: 5:15 - 6:00 P.M. (Must be sober 24 hours, must attend at least 1 recovery focused meeting per week)",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "2022 Boren Avenue, Seattle",
      "Location": "2022 Boren Avenue, Seattle",
      "Name_of_Program": "Recovery Café"
    },
    {
      "Sunday": "",
      "Monday": "5:30:00 PM",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "5:30:00 PM",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Monday & Fridays: 5:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "8201 10th Ave South, Seattle",
      "Location": "8201 10th Ave South, Seattle",
      "Name_of_Program": "South Park Senior Meals"
    },
    {
      "Sunday": "5:30:00 PM",
      "Monday": "5:30:00 PM",
      "Tuesday": "5:30:00 PM",
      "Wednesday": "5:30:00 PM",
      "Thursday": "5:30:00 PM",
      "Friday": "5:30:00 PM",
      "Saturday": "5:30:00 PM",
      "Duration_Hours": 1,
      "Day_Time": "Daily: 5:30 - 6:30 P.M. (No chapel requirement unless staying as a overnight guest)",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "318 2nd Ave. S. Extension,  Seattle",
      "Location": "318 2nd Ave. S. Extension,  Seattle",
      "Name_of_Program": "Union Gospel Mission"
    },
    {
      "Sunday": "",
      "Monday": "6:00:00 PM",
      "Tuesday": "6:00:00 PM",
      "Wednesday": "6:00:00 PM",
      "Thursday": "6:00:00 PM",
      "Friday": "6:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 0.5,
      "Day_Time": "Monday - Friday: 6:00 - 6:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "Youth 13-21",
      "Address": "1828 Yale Avenue",
      "Location": "1828 Yale Avenue (on the corner of Denny and Stewart)",
      "Name_of_Program": "Youth Care's Orion Center"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "6:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Fridays: 6:00 - 7:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "1415 NE 43rd Street, Seattle",
      "Location": "1415 NE 43rd Street, Seattle (alley entrance)",
      "Name_of_Program": "Friday Feast: ROOTS"
    },
    {
      "Sunday": "6:00:00 PM",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Sundays: 6:00 - 7:00 P.M.; Monday through Wednesday: 7:00 - 8:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "FOR YOUTH 22 OR YOUNGER",
      "Address": "2709 3rd Ave., Seattle",
      "Location": "2709 3rd Ave., Seattle",
      "Name_of_Program": "New Horizons Ministries"
    },
    {
      "Sunday": "6:30:00 PM",
      "Monday": "6:30:00 PM",
      "Tuesday": "6:30:00 PM",
      "Wednesday": "6:30:00 PM",
      "Thursday": "6:30:00 PM",
      "Friday": "6:30:00 PM",
      "Saturday": "6:30:00 PM",
      "Duration_Hours": "",
      "Day_Time": "Daily: 6:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO MEN 50+",
      "Address": "1561 Alaskan Way S., Seattle",
      "Location": "1561 Alaskan Way S., Seattle",
      "Name_of_Program": "Saint Martin's de Porres Shelter"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "1st Sunday of each month 6:00 - 7:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Neighborhood Cooking Foundation"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 2,
      "Day_Time": "4th Saturday: 6:30 - 8:30 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Snoqualmie Valley Alliance Church"
    },
    {
      "Sunday": "5:45:00 PM",
      "Monday": "5:45:00 PM",
      "Tuesday": "5:45:00 PM",
      "Wednesday": "5:45:00 PM",
      "Thursday": "5:45:00 PM",
      "Friday": "5:45:00 PM",
      "Saturday": "5:45:00 PM",
      "Duration_Hours": "",
      "Day_Time": "Everyday:  Dinner Intake at 5:45 P.M.  (Required chapel attendance before meal at 8pm)",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "97 South Main St.,  Seattle",
      "Location": "97 South Main St.,  Seattle",
      "Name_of_Program": "Bread of Life Mission"
    },
    {
      "Sunday": "",
      "Monday": "7:00:00 PM",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Mondays: 7:00 - 8:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "Youth 13-25",
      "Address": "University Lutheran Church, N.E. 50th & 16th N.E., Seattle",
      "Location": "University Lutheran Church, N.E. 50th & 16th N.E., Seattle (Enter down the steps off 16th & 50th)",
      "Name_of_Program": "University Street Ministry Teen Feed"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "7:00:00 PM",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Tuesdays: 7:00 - 8:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "Youth 13-25",
      "Address": "University Methodist, N.E. 43rd & 15th N.E., Seattle",
      "Location": "University Methodist               N.E. 43rd & 15th N.E., Seattle (Enter via alley, southwest corner of the bldg)",
      "Name_of_Program": "University Street Ministry Teen Feed"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "7:00:00 PM",
      "Thursday": "7:00:00 PM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Wednesday & Thursday: 7:00 - 8:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "Youth 13-25",
      "Address": "University Congregational, N.E. 45th & 16th N.E., Seattle",
      "Location": "University Congregational     N.E. 45th & 16th N.E., Seattle (Down the seps off 16th)",
      "Name_of_Program": "University Street Ministry Teen Feed"
    },
    {
      "Sunday": "7:00:00 PM",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "7:00:00 PM",
      "Saturday": "",
      "Duration_Hours": 1,
      "Day_Time": "Fridays & Sundays: 7:00 - 8:00 P.M. (Enter via alley, SW corner of building)",
      "Meal_Served": "Dinner",
      "People_Served": "Youth 13-25",
      "Address": "University Christian, N.E. 50th & 15th N.E., Seattle",
      "Location": "University Christian                  N.E. 50th & 15th N.E., Seattle",
      "Name_of_Program": "University Street Ministry Teen Feed"
    },
    {
      "Sunday": "",
      "Monday": "7:30:00 PM",
      "Tuesday": "7:30:00 PM",
      "Wednesday": "7:30:00 PM",
      "Thursday": "7:30:00 PM",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": 1.5,
      "Day_Time": "Monday - Thursday: 7:30 - 9:00 P.M.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Lord's Table"
    },
    {
      "Sunday": "6:00:00 PM",
      "Monday": "6:00:00 PM",
      "Tuesday": "6:00:00 PM",
      "Wednesday": "6:00:00 PM",
      "Thursday": "6:00:00 PM",
      "Friday": "6:00:00 PM",
      "Saturday": "6:00:00 PM",
      "Duration_Hours": 1.25,
      "Day_Time": "Daily: 6:00 - 7:15 pm",
      "Meal_Served": "Dinner",
      "People_Served": "WOMEN 18 AND OLDER",
      "Address": "2030 3rd Ave, Seattle",
      "Location": "2030 3rd Ave, Seattle",
      "Name_of_Program": "Women's Referral Center"
    },
    {
      "Sunday": "",
      "Monday": "",
      "Tuesday": "",
      "Wednesday": "",
      "Thursday": "",
      "Friday": "",
      "Saturday": "",
      "Duration_Hours": "",
      "Day_Time": "Major Holidays Only, Thanksgiving, Christmas, New Years day.",
      "Meal_Served": "Dinner",
      "People_Served": "OPEN TO ALL",
      "Address": "6th and Columbia, Seattle",
      "Location": "Outdoor Meal Site at 6th and Columbia, Seattle",
      "Name_of_Program": "Friends of Francois"
    }
]

for (let i=0; i<3; i++) {
    let newLocation = new locations(dataset[i]);
    newLocation.save(function(err) {
        if (err) {
            console.log(err);
        }
    });
}
console.log("Done");